### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by jslvtr** [react-tools/react-table#530] opened 2017-10-03 12:11 UTC
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
It doesn't look like `react-table` has RTL support. It would include:

- Reversing direction of content in cells;
- Reversing order of columns in table;
- Reversing prev/next pagination buttons;
- Probably more things I'm not thinking about.

Is this something we're thinking about doing? It's a hard constraint on my use case.

**Comment by gary-menzel** [comment] 2017-10-04 00:25
Firstly, the design goal of react-table is lightweight so it is not going to have every feature in it. But it is very rich in allowing you to customise it.

Of the list you have provided:

- RTL text direction is a CSS thing - so you should be able to override cell props for this
- You can order the columns any way you like in your columns array
- prev/next - nothing in the box but you could create your own `PaginationComponent`
- "more things" - would need to know what they are but many would be possible through all the component and prop hooks the solution exposes.

These are all customisations that can be done - and you could build a HoC to do these so you can reuse it by wrapping any ReactTable with the HoC.

**Comment by gary-menzel** [comment] 2017-10-06 07:51
Suggest adding the ability to "switch" the prev/next buttons to provide assistance for RTL use.

**Comment by webernir** [comment] 2017-10-31 09:47
I also face issues with RTL support (when having `direction: rtl`).

one issue is that horizontal scroll is not working as expected.
I was able to fix that by using:

```javascript
<ReactTable
   getTableProps={() => ({ style: { display: 'block' } })} // direction: rtl fix
/>
```

[see demo](https://codesandbox.io/s/6192oy79zz)

![react-table-scroll](https://user-images.githubusercontent.com/2412543/32217544-fcc615e0-be30-11e7-8d6d-ca32152e735a.gif)

**Comment by atlanteh** [comment] 2017-12-14 20:25
@webernir Thank u! This happened to me too, and u just saved me!
@gary-menzel is there any way to fix this to have it working both for ltr & rtl?

**Comment by gary-menzel** [comment] 2017-12-14 20:52
@atlanteh I am not quite sure what you mean.  At present, there is no official support for RTL other than what you can do by overriding the CSS.  So far, the answers contributed in this issue are as much as we know.

For the switching of the buttons, you still need to code your own Pagination component.

I'm not even sure what the more recent suggestion (for scrolling) would do across all the different browsers.

**Comment by atlanteh** [comment] 2017-12-14 21:58
Well, I'm not saying full support for RTL, but if the suggested css is good for both ltr & rtl, then maybe you can use that instead of the current implementation.

My problem was a little bit different than what was shown in the demo. My problem was that even though there was enough space, my table always had horizontal overflow. Once applying the fix, the scrolling disappeared.

**Comment by gary-menzel** [comment] 2017-12-14 22:09
That's where the issue is - the current CSS is fairly finely tuned and relies heavily on `flex`.  So changing the `display` from `flex` to `block` may have unintended consequences.  To make such a top-level change would require extensive testing across a range of browsers to ensure it is backwards compatible or a completely new major version.

Given that this can be easily overridden in the current implementation, it is unlikely to make it into an actual change in the code. Hence why the priority is low.

However it is marked as a feature request that would be considered in any future major updates of the component. Some of the basic principles for a brand new major version are being considered at the moment.

**Comment by Dyedan** [comment] 2018-05-05 17:35
I also suffer from this bug using the latest version of react-table, I hope this will be fixed soon!

**Comment by gary-menzel** [comment] 2018-05-05 22:28
There are no intentions to "fix" this in the current version.  If your requirement depends on RTL support then you should probably consider a different table package.

Even in the next major re-write there may be no support for RTL (the thinking is currently that all of the styling and extraneous functionality - like pagination controls - will be stripped out into separate modules and will need to be plugged in or created by the developer).

It remains as a LOW priority.

**Comment by tannerlinsley** [comment] 2018-05-24 22:41
Closing for now. There is no plan to include any more RTL support than is already possible within the scope of React-Table.

**Closed by tannerlinsley** 2018-05-24 22:41 UTC
Labels: Feature Request, Priority:Low

**Comment by jajool** [comment] 2019-03-13 10:33
hi 
now that version 7 is in pre alpha stage could you add @webernir css to master.
or at least in the documentation add a section for rtl languages if you want i can create a PR to update documentation with some examples.

**Comment by dadwic** [comment] 2020-09-17 09:00
https://github.com/tannerlinsley/react-table/pull/2733

**Comment by erfanesfahani** [comment] 2023-09-09 15:47
Hello All
Any update from resizing direction issue ? 
it's not related to CSS
as per my view this method is not directional => getResizeHandler
