### ISSUE TITLE
Sticky columns

### ISSUE THREAD

**Issue by visarts** [react-tools/react-table#848] opened 2018-03-08 14:00 UTC
Is there any plan to add a feature for fixed or 'sticky' columns allowing for horizontal scrolling, in addition to vertical

**Comment by rickevans** [comment] 2018-03-08 14:10
I have this same problem as I would like to have the first two columns fixed in my table and have the rest of the table contents scroll

**Comment by meteorplus** [comment] 2018-03-08 14:39
nice to have

**Comment by gary-menzel** [comment] 2018-03-09 02:28
There are no sticky columns.  The package needs a complete redesign for this. Sorry.

**Comment by OliverKK** [comment] 2018-03-27 20:05
Hello @gary-menzel ,
can you estimate how much effort that would mean? 
We are thinking about funding the development of the feature. 
I think there are many users who might need this feature. 

What are u guys think?
@jsonmaur 
@sghall

**Comment by dvdhsu** [comment] 2018-04-02 06:14
We would probably fund this with a few hundred $.

**Comment by gary-menzel** [comment] 2018-04-02 06:20
You'll have to talk to @tannerlinsley in regard to any paid-for development.  My commercial rate is $100 per hour and I doubt a "few hours" will get this done as the whole architecture of ReactTable needs to be changed to do it (and I don't have the available hours to do a re-architect of RT).  Seriously - if it were that easy it would already be done (others - including myself - have tried to do it in the current design and it just not feasible).

**Comment by tannerlinsley** [comment] 2018-04-02 06:26
It would require upwards of at least 5k paid work to do this. As they have
said, this would require an architecture redesign that could take a month
at least.

**Comment by meteorplus** [comment] 2018-04-02 06:32
$3k and I'll do it in less than a week!

**Comment by tannerlinsley** [comment] 2018-04-02 06:35
If someone does decide to take this on be sure to outline the architecture
redesign in a proposal so Gary and I can approve it ultimately merge it.
Would hate to see someone spin their wheels on paid open source!

**Comment by dvdhsu** [comment] 2018-04-02 06:41
Sorry - I didn't mean to imply a "few hours" would cut it - I know this is a big feature! But we would chip in a few hundred... and with 10 or so of us - that might be enough!

Agreed about open sourcing the results and checking with @tannerlinsley + @gary-menzel about it first.

So - is there anybody else willing to contribute?

**Comment by meteorplus** [comment] 2018-04-02 17:21
tell me your price and I will do it ;) @dvdhsu

**Comment by OliverKK** [comment] 2018-04-03 12:53
@dvdhsu 
Yes. We are willing to contribute also.

What about starting a kickstarter project to fund this feature?

**Comment by meteorplus** [comment] 2018-04-05 04:04
I've got a good demo for you guys
Sticky Column Fixed First column:
https://share.vidyard.com/watch/JNbLj1xorzwgMMU4JxQtvt


Sticky Header Vertical Scroll

https://share.vidyard.com/watch/bP3Aqa9aYw1yFysT1W9nec

Although someone needs to fund this so I can release this and send a PR...

Thanks

**Comment by JohanDuque** [comment] 2018-04-09 13:36
It would be great to have not only the first column sticky but also a customisable one (the last one for example)

**Comment by meteorplus** [comment] 2018-04-09 18:54
Totally, what would be way better is to choose which columns by index like this

Any suggestions are welcome :)
```
        <ReactTable
          data={data}
          pageSize={200}
          columns={columns}
          fixedColumns={1}//can be any index of a column
          defaultPageSize={10}
          className="-striped -highlight"
        />
```

I would love to do that too and release it this week... for just $1500?

Thanks

**Comment by ahmedhosny** [comment] 2018-04-11 19:06
Great repo over here - but I opted to use [scrollsync in react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/ScrollSync) for this specific purpose.

**Comment by meteorplus** [comment] 2018-04-11 19:33
@ahmedhosny yes looks the same as I did but that is too much extra code for just one simple thing that can be done without adding any extra library...

**Comment by OliverKK** [comment] 2018-04-20 11:31
Hi @GuillaumeJasmin , 
thank you. The first tests passed so far. I'll give it a try.
I will have a closer look at the extension in the next days.

Kind regards

**Comment by meteorplus** [comment] 2018-04-23 17:58
@GuillaumeJasmin thanks mate but listen I never abused anyone! even the author suggested a hourely rate before I jumped in and even @OliverKK offered to fund this!

and keep in mind not everyone has a stable job or a monthly salary...

we hustle like this so we can pay our bills, and this is how open source works!

otherwise, I am gonna release this into my repo https://github.com/meteorplus/react-table for free, I don't give a fuck if it wasn't for my rent else I won't care.

**Comment by Oleksandr-Silin** [comment] 2018-04-26 06:38
@meteorplus Hey, just wondering, have you released your changes?

**Comment by pmusaraj** [comment] 2018-05-10 15:15
I wound up using a semi-simple solution to do this for one frozen column (Guillaume's HOC supports multiple), it involves a few steps: 

1. In your column's definition, add `className: 'frozen'` and `headerClassName: 'frozen'`. 

2. In your css add the following: 

````
      .rt-tr {
        position: relative;
      }
      .frozen {
        position: absolute;
        left: 0px;
        background: #F8F8F8;
        height: 36px;
        transition: left 0.2s;
      }

      .rt-th.frozen {
        z-index: 2;
        height: 34px;
      }

````
(YMMV, some of the styles above are specific to my use. Like the height of the cells, for example. You may also need to add some more styles to make this work with striping and highlighting.) 

3. Add a callback to the ReactTable's `onResizedChange`. For example: 

````
        <ReactTable
          onResizedChange={_.debounce(this.onTableResizeChange, 10)} 
          ... />
````

(Notice that I'm using Underscore's debounce to avoid calling this too often on a resize.)
And the `onTableResizeChange` looks like this: 

````
  onTableResizeChange(params) {
    let frozenCol = this.state.frozenColumn,
        padLeft = 0;

    if (frozenCol) {
      if (params && params[0].id === frozenCol) {
        padLeft = params[0].value;
      } else {
        padLeft = $('.ReactTable .rt-th.frozen').width() + 10;
      }

      $('.ReactTable .rt-tr').css('padding-left', padLeft + 10);
    } else {
      $('.ReactTable .rt-tr').css('padding-left', 0);
    }
  }
````

So, this will make sure that the frozen column can be resized and that the other table columns will adjust accordingly.

4. Final step: add an `onScroll` event to the table properties, and then change the position of the absolutely positioned column, so that it looks frozen in place. 

````
      <ReactTable
          getTableProps={() => {
            return {
              onScroll: (e) => {
                if (this.state.frozenColumn) {
                  if (this.tableScrollTop === e.target.scrollTop) {
                    let left = e.target.scrollLeft > 0 ? e.target.scrollLeft - 12 : e.target.scrollLeft;
                    $('.ReactTable .rt-tr .frozen').css({left: left});
                  } else {
                    this.tableScrollTop = e.target.scrollTop;
                  }
                }
              }
            };
          }}
      ... />
````

Note that the onScroll relies on `this.tableScrollTop` to only change the position of the frozen elements when scrolling horizontally. `this.tableScrolltop` is initialized in the constructor, like so: 

````
  constructor(props){
    super(props);
    this.tableScrollTop = 0;
  }
````

**Comment by krzysiek1507** [comment] 2018-05-10 19:57
You can use [`position: sticky`](https://caniuse.com/#feat=css-sticky) to do it. [Example](https://codesandbox.io/s/n766xny1o0)

**Comment by datanotion** [comment] 2018-05-11 15:37
The solution from @krzysiek1507 worked for me.  Next I'm going to try to determine how to freeze the grouping header as well.  Thank you!

**Comment by krzysiek1507** [comment] 2018-05-11 16:53
No, it doesn't work. Sorry! It breaks the table!

There is a problem with `overflow: auto` and `position: sticky`. Maybe some CSS master can fix it.

**Comment by meteorplus** [comment] 2018-05-11 17:00
@krzysiek1507 @Oleksandr-Silin here is my solution 

https://codesandbox.io/s/pk19p2pm17
The first column is locked I don't have time to add it to the repo but you have the whole css there working fine with all browsers out there no stick or fancy css.

If I find the other horizontal lock for the first rows I will post it here too thanks.

**Comment by GuillaumeJasmin** [comment] 2018-05-11 19:25
I currently work on support of fixed group header in `react-table-hoc-fixed-columns` . I think release it in few days.

**Comment by pmusaraj** [comment] 2018-05-16 15:10
I worked a slightly lighter and better solution (mostly due to a bug in Safari). Here is the sandbox: https://codesandbox.io/s/k9n3y82wov 

I tested on Safari/Chrome/Firefox. The frozen column can be any column, and all columns can be resized.

**Comment by tannerlinsley** [comment] 2018-05-24 22:54
There is no direct roadmap to support Sticky Columns in the latest version of React Table.

**Closed by tannerlinsley** 2018-05-24 22:54 UTC

**Comment by GuillaumeJasmin** [comment] 2018-07-13 16:33
Hi,
I released a `v1` beta of `react-table-hoc-fixed-columns`.

### new features
* fixed columns groups
* fixed columns on the left and/or right side
* complete refactoring, no more DOM and CSS hacks, so better performances

You can install it with the tag `next`:
```
npm install react-table-hoc-fixed-columns@next
```

### Demo
https://codesandbox.io/s/jnjv6j495y

### Release note
https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/releases/tag/v1.0.0-beta.3

### Docs
https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/tree/next

**Comment by timendez** [comment] 2018-07-13 22:50
Using `position: sticky` will work as per @krzysiek1507's example, and you can polyfill for unsupported browsers with https://github.com/wilddeer/stickyfill

**Comment by GuillaumeJasmin** [comment] 2018-07-13 22:58
`position: sticky` doesn't work for me with 2 fixed columns, or with fixed groups

**Comment by ykantamaneni** [comment] 2018-07-17 23:56
@GuillaumeJasmin does v1 beta of react-table-hoc-fixed-columns support fixed header as well or just fixed column?

Thanks

**Comment by GuillaumeJasmin** [comment] 2018-07-18 08:59
fixed header or fixed group header ? fixed header (vertical scrolling) works by default in ReactTable.
`react-table-hoc-fixed-columns` add support for fixed columns, and fixed columns with header group

**Comment by GuillaumeJasmin** [comment] 2018-09-01 02:05
Stable v1 of fixed columns HOC is just release

Demo: https://codesandbox.io/s/jnjv6j495y

Source & docs: https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns

**Comment by epicfaace** [comment] 2019-01-14 16:23
@tannerlinsley -- now that we have the fixed columns HOC by @GuillaumeJasmin , is this something that could potentially be merged as a feature in react-table?

**Comment by piotrkochan** [comment] 2020-02-12 14:55
@GuillaumeJasmin does not work with react v7.0.0

**Comment by GuillaumeJasmin** [comment] 2020-02-16 21:32
@piotrkochan issue already addressed here [react-table-hoc-fixed-columns/issues/53](https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/issues/53)

I just start [react-table-sticky](https://github.com/GuillaumeJasmin/react-table-sticky) which is for react-table v7

**Comment by nitishnivedan** [comment] 2020-10-22 18:27
@GuillaumeJasmin  
Hi,

I am using this react-table-hoc-fixed-column to freeze certain columns. My each row in the table has inline edit (For ex. in each row, one column has dropdown).

The problem with this hoc is when I change value of any row's drop down it comes back to first page (like a fresh render).

For example I am in page 2 and i edit any row then it comes back to 1st page. Although data is being retained.

Will really appreciate any lead.

"react-table": "^6.10.3",
"react-table-hoc-fixed-columns": "^2.3.3",

[Note: my code works totally fine when I use the react-table, it doesnt come back to first page]

**Comment by nkpremices** [comment] 2021-04-08 23:37
Anyone knows how to achieve this with version 7 ?

**Comment by jcortes0309** [comment] 2021-05-14 22:41
@nkpremices, check the `react-table-sticky` repository @GuillaumeJasmin mentioned

> @piotrkochan issue already addressed here [react-table-hoc-fixed-columns/issues/53](https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/issues/53)
> 
> I just start [react-table-sticky](https://github.com/GuillaumeJasmin/react-table-sticky) which is for react-table v7

**Comment by bryantobing12** [comment] 2022-09-15 12:05
are there any implementation with v8?

**Comment by KevinVandy** [comment] 2022-09-15 13:21
> is there any implementation with v8?

You just have to add position sticky to pinned columns themselves, and use the "start" properties on a column's `left` css

You'll get something like this https://www.material-react-table.dev/?path=/story/features-column-pinning-examples--column-pinning-initial

**Comment by ailequal** [comment] 2022-11-17 16:12
I am working with `"@tanstack/table-core": "8.2.6"` and I was able to stick a column to either left or right by following this example "https://stackoverflow.com/a/53526213/19879825". Just some CSS rules and the table seems to keep working fine.

**Comment by x5engine** [comment] 2023-04-06 09:11
Hello guys, so what solution did you choose?

**Comment by sanjay-git** [comment] 2023-04-26 19:06
> > is there any implementation with v8?
> 
> You just have to add position sticky to pinned columns themselves, and use the "start" properties on a column's `left` css
> 
> You'll get something like this https://www.material-react-table.dev/?path=/story/features-column-pinning-examples--column-pinning-initial

@KevinVandy, could you expand a bit more on what you mean by "start" properties ? I am trying to add sticky behavior to more than one column, but finding it difficult to set the 'left' property for columns other than the first one. Thanks in advance!

**Comment by paweljurczynskiflyr** [comment] 2023-06-08 07:13
> > > is there any implementation with v8?
> > 
> > 
> > You just have to add position sticky to pinned columns themselves, and use the "start" properties on a column's `left` css
> > You'll get something like this https://www.material-react-table.dev/?path=/story/features-column-pinning-examples--column-pinning-initial
> 
> @KevinVandy, could you expand a bit more on what you mean by "start" properties ? I am trying to add sticky behavior to more than one column, but finding it difficult to set the 'left' property for columns other than the first one. Thanks in advance!

I'm on a similar problem right now. And I just thinking about setting ref to get the physical element and get that `offsetLeft` and `offsetRight`. And for async rendering use `resizeObserver` and update that accordingly. 

I'm not sure if it's a best solution at this moment 😢

**Comment by HurYur** [comment] 2023-08-04 13:17
I was expecting that `Column Pinning` would stick the column to the side during the horizontal scrolling, but it doesn't do it as well.

**Comment by Husain010** [comment] 2023-08-31 11:23
> I was expecting that `Column Pinning` would stick the column to the side during the horizontal scrolling, but it doesn't do it as well.

Any workarounds? I want to achieve the same but cannot find anything

**Comment by KevinVandy** [comment] 2023-08-31 17:31
> > I was expecting that `Column Pinning` would stick the column to the side during the horizontal scrolling, but it doesn't do it as well.
> 
> Any workarounds? I want to achieve the same but cannot find anything
> 

You have to provide the CSS to do that yourself, of course. Position sticky and all that. TanStack Table keeps track of which columns are pinned

**Comment by Husain010** [comment] 2023-09-01 10:53
> > > I was expecting that `Column Pinning` would stick the column to the side during the horizontal scrolling, but it doesn't do it as well.
> > 
> > 
> > Any workarounds? I want to achieve the same but cannot find anything
> 
> You have to provide the CSS to do that yourself, of course. Position sticky and all that. TanStack Table keeps track of which columns are pinned

I actually was able to achieve it with CSS itself! No pinning also required ( Had to have the right 0hand most column sticky for horizontal scroll)

**Comment by GlebKodrik** [comment] 2023-10-17 20:27
If you don't mind, please show me how you fixed the columns in the codesandbox or another sandbox

I've been trying to do this for a long time and it doesn't work at all. I would really appreciate some help

**Comment by Nikolic-Marko** [comment] 2023-10-19 12:25
Hi guys, same issue here. I see that this was discussed 5years ago, are there any plans maybe to implement this now on version 8, or should we go with the hacky solution?

**Comment by mpcen** [comment] 2023-11-04 15:26
It's 2023. We need this feature

**Comment by tannerlinsley** [comment] 2023-11-04 19:11
What’s stopping you from putting a sticky style on the first column cells? We do this and it works just fine.

Tanner Linsley

**Comment by mpcen** [comment] 2023-11-09 17:06
> What’s stopping you from putting a sticky style on the first column cells? We do this and it works just fine. Tanner Linsley
> […](#)
> On Nov 4, 2023 at 9:26 AM -0600, Manny Martinez ***@***.***>, wrote: It's 2023. We need this feature — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

just seems like a hack tbh. im able to successfully sticky 1 column but having trouble stickying multiple

**Comment by andresgutgon** [comment] 2023-11-10 08:34
> What’s stopping you from putting a sticky style on the first column cells? We do this and it works just fine.

We have a virtualized table. Would be that a solution in that case?

**Comment by tomasmenezes** [comment] 2023-11-14 23:32
+1, The process could be facilitated for multi-column pinning styling and virtualization cases

**Comment by Khangeldy** [comment] 2023-11-24 07:22
If someone want multiple sticky columns. You can use `getStart` method on columns. I found it accidently on documentation. And there no mention about it. 
Fast example: 
```
const sticky = ['name', 'age']
...
headers.map(header => {
return <th style={sticky.includes(header.id) ? {{ left:  header.getStart('left'), position: 'sticky', top: 0 } : {}}>{header.column.columnDef.header}</th>
```
You are welcome ! Thanks to great library 👍

**Comment by GlebKodrik** [comment] 2023-12-03 23:41
Here is my solution for docked columns https://github.com/GlebKodrik/table

**Comment by Florinstruct** [comment] 2023-12-08 17:00
> Here is my solution for docked columns https://github.com/GlebKodrik/table
> 
> There in the readme there is a link to the assembly, which you can follow and see whether or not. In this link, the column has a menu “Fix column”, you can poke it and try scroll

How do I find the "Fix column" without learning Russian?

**Comment by andresgutgon** [comment] 2023-12-08 17:28
> How do I find the "Fix column" without learning Russian?

Not the way to go in an Open Source community imo. @GlebKodrik give us a solution. We can look into the code which is still javascript.

**Comment by Florinstruct** [comment] 2023-12-11 07:49
> > How do I find the "Fix column" without learning Russian?
> 
> Not the way to go in an Open Source community imo. @GlebKodrik give us a solution. We can look into the code which is still javascript.

Well if you can't follow the example because it's in Russian that's a problem.

**Comment by andresgutgon** [comment] 2023-12-11 08:07
But you know how to read javascript. Don't you?

**Comment by Florinstruct** [comment] 2023-12-11 08:34
> But you know how to read javascript. Don't you?

I'm not quite sure why you're trying to turn this into a cake fight. @GlebKodrik posted an example that is not usable unless you speak Russian so I asked how to find the button he mentioned. If you can't help with that, please don't post toxic comments at me.

**Comment by andresgutgon** [comment] 2023-12-11 08:45
You're right, I don't want to make this thread a toxic place. So I'll stop talking. Just for clarification I started this discussion because the way you speak to him sounded not ok

> How do I find the "Fix column" without learning Russian?

That you don't know Russian (neither do I) is not his problem. He did a great work finding a solution. We can just look into the code. To me this is so obvious that I can't understand why we're having this discussion in the first place. I don't want to end this with an ad-hominen comment but looking at your profile you look like a fake account trolling a bit. 

Anyway, again you're right I'm not helping here so I'll stop talking. Sorry to the rest 🙏

**Comment by GlebKodrik** [comment] 2023-12-26 12:16
If you want to see the visual part, I have translated everything into English. If you don’t understand how to reproduce cases on the site (because it’s Russian), just translate the page

If we are talking about code, then there are no problems there, JavaScript

Also, if you debug everything, you can find it without knowing the language
I just decided to show the solution I managed to make

**Comment by edprats** [comment] 2024-01-21 22:38
going to post this hacky solution in case it helps anyone in the future

in my situation i wanted to just have the first column always sticky on scroll so i added a `custom-column-sticky` css class to the `td` element.

and the css is the following:

```
td:first-of-type.custom-column-sticky {
  position: sticky;
  left: 0;
  top: 0;
}
```

**Comment by SurendarSingh** [comment] 2024-01-23 14:06
You can add sticky properties for a column in the className into column meta.

```jsx
import "@tanstack/react-table";
import { RowData } from "@tanstack/react-table";

declare module "@tanstack/react-table" {
  interface ColumnMeta<TData extends RowData, TValue> {
    className: string;
  }
}

const columns = [
    {
      header: "Sticky Column",
      accessorKey: "stickyColumn",
      meta: {
        className:
          "sticky right-0",
       },
    },
// other columns
]



//Then, you can get it through the column.columnDef.meta?.className. Add the className in th and td tag.
<th
className={`${
header.column.columnDef.meta?.className ?? ""
} 
// other tailwind CSS properties
`}
key={header.id}
colSpan={header.colSpan}
>
<td
key={cell.id}
className={`${
cell.column.columnDef.meta?.className ?? ""
} 
// other tailwind CSS properties
`}
>

```

**Comment by donlair** [comment] 2024-02-21 18:13
I was just working on this issue and put together a [small repo](https://github.com/donlair/sticky-table-demo/tree/main) to demonstrate my solution that allows you to make multiple columns sticky:

![CleanShot 2024-02-21 at 13 12 20](https://github.com/TanStack/table/assets/35781181/33042cd9-6a14-4824-a97a-b1465a3ab046)

**Comment by KevinVandy** [comment] 2024-02-21 21:02
> I was just working on this issue and put together a [small repo](https://github.com/donlair/sticky-table-demo/tree/main) to demonstrate my solution that allows you to make multiple columns sticky:
> 
> ![CleanShot 2024-02-21 at 13 12 20](https://github.com/TanStack/table/assets/35781181/33042cd9-6a14-4824-a97a-b1465a3ab046)
> 

There's also an official example for sticky column pinning in the docs
https://tanstack.com/table/latest/docs/framework/react/examples/column-pinning-sticky

**Comment by Ignacio1996** [comment] 2024-04-29 13:20
Hey all, without making any changes to react-table, we found a very simple solution:

Just create 2 tables, one with one column, the other with the rest of your columns and an horizontal overflow container. 

This fixes the issue, we know it's not the best solution, and the latest version of react-table probably has a fix for this. But if you're using an older version (we are), 2 tables is the answer. Make sure that each table has it's own div container, and the do a flex-row for the container of the 2 tables. 

Hope that helps!

**Comment by KevinFalah** [comment] 2024-05-25 12:16
I have some solution, you must have some key in columns like this (in my code is "sticky:true")

`export const columns = () => [
  {
    Header: "No",
    accessor: "No",
    Cell: ({ row }) => {
      return (
        <div className="font-medium text-black flex items-center gap-x-2 text-base">
          {row?.index + 1}
          <Checkbox />
        </div>
      );
    },
  },
  {
    Header: "NIM",
    accessor: "nim",
    sticky: true,
    Cell: ({ value }) => {
      return (
        <div className="font-medium text-black flex items-center gap-x-2 text-base">
          {value ?? "-"}
        </div>
      );
    },
  },
  ]`
  
  so in the table you have to add some logic :
  
  `  <th
                      key={j}
                      className=${column?.sticky ? 'sticky left-0 bg-darkBluePrimary' : ''} ${column?.meta?.className ?? ""} text-center px-4`}
                      {...column.getHeaderProps(column.getSortByToggleProps())}
                    >`
                    
                    
here my full table code :                   

`<table
            id="tabel"
            
            className={`w-full ${paginate ? "mb-4" : "mb-3"} rounded-md border`}
            {...getTableProps()}
          >
            <thead className="w-full sticky top-0 z-10 bg-darkBluePrimary rounded-md">
              {headerGroups?.map((headerGroup, i) => (
                <tr
                  key={i}
                  className="rounded-md"
                  {...headerGroup.getHeaderGroupProps()}
                >
                  {headerGroup.headers.map((column, j) => (
                    <th
                      key={j}
                      className={`text-left text-sm font-medium ${
                        column?.Header !== "Action" &&
                        column?.Header !== "" &&
                        column?.Header !== "No" &&
                        !column?.minW
                          ? "min-w-[160px] max-w[175px]"
                          : "min-w-[24px]"
                      } ${
                        column.isSorted
                          ? column.isSortedDesc
                            ? "sort-desc"
                            : "sort-asc"
                          : ""
                      } ${column?.sticky ? 'sticky left-0 bg-darkBluePrimary' : ''} ${column?.meta?.className ?? ""} text-center px-4`}
                      {...column.getHeaderProps(column.getSortByToggleProps())}
                    >
                      <span
                        className={`text-white text-lg font-medium my-4 inline-block`}
                      >
                        {column.render("Header")}
                      </span>
                    </th>
                  ))}
                </tr>
              ))}
            </thead>
            <tbody
              className={remoteLoading ? "pointer-events-none" : ""}
              {...getTableBodyProps()}
            >
              {page.map((row, i) => {
                prepareRow(row);
                return (
                  <tr key={i} className="border-b-2 hover:bg-gray-200 sticky left-0" {...row.getRowProps()}>
                    {row.cells.map((cell, j) => {
                      console.log(cell?.column?.sticky ,"<--- celll")
                      return (
                        <td
                          key={j}
                          className={`${cell?.column?.sticky ? 'sticky left-0 bg-white' : ''} px-4 py-2 font-medium text-sm text-center`}
                          {...cell.getCellProps()}
                        >
                          {cell.render("Cell")}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>`
          
          
          i hope this usefull

**Comment by EwenQuim** [comment] 2024-10-01 17:36
The @donlair solution works but there's a catch that you can see on this video: https://www.loom.com/share/8b18fa431b4d4390883ef31ec2361aa2?sid=e845e793-01ab-4e71-9c27-ed42854ea81d

The second column is overlapping the first one when scrolling right. Just run [the repo](https://github.com/donlair/sticky-table-demo/tree/main) provided by donlair and it happens. I'm guessing that `column.getStart()` does not always return the correct value, even though it works perfectly on the [official docs example](https://tanstack.com/table/v8/docs/framework/react/examples/column-pinning-sticky).

A bit frustrating, i'm investigating that.

**Comment by rishitank** [comment] 2024-11-22 15:09
On a related question, does anyone know how to have expanded rows with sticky columns? Ideally I want the expanded row content (using a custom component) to stay in place while everything except the sticky columns are horizontally scrollable. Is it doable? I am using React Table v7.
