### ISSUE TITLE
Migrate away from componentWillMount and componentWillReceiveProps

### ISSUE THREAD

**Issue by heikkilamarko** [react-tools/react-table#888] opened 2018-03-30 10:50 UTC
The latest React discourages using `componentWillMount` and `componentWillReceiveProps`.
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by gary-menzel** [comment] 2018-03-30 13:00
React Table supports 15 and 16.  They are still valid lifecycle methods. They have only recently fallen into disfavour.  There are currently no resources working on code changes like this for React Table but you are welcome to submit a PR.

**Comment by tannerlinsley** [comment] 2018-05-24 22:47
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!

**Closed by tannerlinsley** 2018-05-24 22:47 UTC

**Comment by ashnur** [comment] 2019-08-09 16:59
Not sure why do you think that the problem will solve itself. It will not. https://fb.me/react-strict-mode-warnings

**Comment by tannerlinsley** [comment] 2019-08-09 17:41
How or why would this issue solve itself exactly?

**Comment by tannerlinsley** [comment] 2019-08-09 17:44
React Table doesn't use classes or lifecycles anymore. If you're using an older version that does, then you'll need to either upgrade or fork and fix

**Comment by ashnur** [comment] 2019-08-09 19:03
https://github.com/tannerlinsley/react-table/blob/v6/src/lifecycle.js latest is 6.10 which has lifecycles. I am not sure if you mean that I should use @next or what.

**Comment by JanBojko** [comment] 2019-08-25 17:32
I see the warning as well with the version 6.10, it has appeared with an upgrade to React 16.9.  I am just curious if the upcoming version 7.0 is going to handle it. The issue is closed already, sorry I just hit it :-).

**Comment by tannerlinsley** [comment] 2019-08-25 18:31
V7 is not affected by this issue.

Tanner Linsley
