### ISSUE TITLE
The example of custom filtering is not working

### ISSUE THREAD

**Issue by arimourao** [react-tools/react-table#553] opened 2017-10-16 13:53 UTC
The sample code for "Custom Filtering" is not working as it should for the column "First Name". All other columns seems to be working fine.

https://react-table.js.org/#/story/custom-filtering

**Comment by gary-menzel** [comment] 2017-10-16 23:06
Confirmed. The && should be a || in the `filterMethod` for `firstName`. Low priority change due to it being in the examples.

**Comment by piyuesh-dev** [comment] 2018-01-12 05:41
I'll do it.

**Comment by piyuesh-dev** [comment] 2018-01-12 06:41
Submitted PR 739.

**Comment by tannerlinsley** [comment] 2018-05-24 22:44
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!

**Closed by tannerlinsley** 2018-05-24 22:44 UTC
Labels: Example Bug, Priority:Low
