### ISSUE TITLE
Restrict sorting to column header onClick.

### ISSUE THREAD

**Issue by idlefun** [react-tools/react-table#971] opened 2018-05-15 16:12 UTC
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
Table sorts onBlur. Is it possible to only sort when column header is clicked?

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
This issue can be seen in the react-table 'demos and examples' for 'Editable Table': https://react-table.js.org/#/story/editable-table

## What are the steps to reproduce the issue?

1. Change makeData default in Utils to, e.g. 8, for ease of testing. export function makeData(len = 8)
2. Sort table on first column.
3. Edit cell in first column (e.g. row 4).
4. Click Tab to move to next column. 
5. This causes the table to sort. Focused  cell is second column of row 4 but row that was being edited is no longer row 4 due to sort.

**Comment by gary-menzel** [comment] 2018-05-16 00:47
It causes a sort because the data passed in the `props` is changing.  The changed data has to get back into the original data somehow.

The editable content example is just that - and example - it is really up to the Developer to implement all the functionality they want.  So, you just change what you want - using the example as a base.  Maybe you want to put the content into a shadow record and then use a button to "save" the data back in.

Inline editing is not a "core" feature of ReactTable. The example just shows that the basics of doing it. 

So this is not a bug.  Closing.

**Closed by gary-menzel** 2018-05-16 00:47 UTC
