### ISSUE TITLE
Filtering doesn't work on hidden column 

### ISSUE THREAD

**Issue by Glenf** [react-tools/react-table#927] opened 2018-04-26 09:18 UTC
## What version of React-Table are you using?

6.8.2

## What bug are you experiencing, or what feature are you proposing?

I have controlled component which gets filtered state from another component (custom FilterPanel). I have some data (a lot) that I do not wish to show but want to do filtering with. I currently have that data assigned on one column with custom filtering method. If that column is visible the external filtering works. If the column is hidden the filtering doesn't work.

Any way round this limitation? 

Currently I'm "fixing" this by 
```javascript
{
  Header: "",
  Filter: () => false,
  width: 0
  ...
}
```

**Comment by gary-menzel** [comment] 2018-04-26 23:49
This is by design and is not likely to change in the current version.

Most who are filtering externally do it directly against the data before pushing it into ReactTable.

**Comment by tannerlinsley** [comment] 2018-05-24 22:50
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!

**Closed by tannerlinsley** 2018-05-24 22:50 UTC
