### ISSUE TITLE
Your table in demo doesn't work

### ISSUE THREAD

**Issue by wzup** [react-tools/react-table#925] opened 2018-04-24 08:26 UTC
## What version of React-Table are you using?
Your site demo

## What bug are you experiencing, or what feature are you proposing?
Filters do not work. https://react-table.js.org/#/story/custom-filtering

Your initial data. See `rabbits`?

![filters](https://user-images.githubusercontent.com/3880497/39175052-0288786e-47b2-11e8-9cfc-026159c81371.png)

Filtering by `rabbits`. Where is data?

![filters2](https://user-images.githubusercontent.com/3880497/39175104-1df9e538-47b2-11e8-9b7d-78946d851ddd.png)

## What are the steps to reproduce the issue?
1. Visit your own site
2. Select *Custom Filtering* in side menu
3. Type in something in filter input field
4. No results found

**Comment by mhxbe** [comment] 2018-04-24 09:29
This actually works as intended.
If you take a look at the **filterMethod** of the First Name column:
```
{
  Header: "First Name",
  accessor: "firstName",
  filterMethod: (filter, row) =>
    row[filter.id].startsWith(filter.value) &&
    row[filter.id].endsWith(filter.value)
 }
```

You'll see that only the values are shown which are **starting** and **ending** with the given filter.value.
So: 
`ra` won't show `rabbits` because `rabbits` is not ending with `ra`.
But, if you type for example `se`, you will see `sense` because its both starting & ending with `se`.

I hope this makes sense.
Now this means this issue can be closed since this is not a bug.

**Comment by gary-menzel** [comment] 2018-04-24 10:41
I agree - the "demo" is showing how to use various sorting techniques that can be used.  They are not necessarily meant to make `sense`.  Even the data often doesn't match the columns.

You could also just play with the codesandbox and replace:
```
                    row[filter.id].startsWith(filter.value) &&
                    row[filter.id].endsWith(filter.value)
```
with
```
                    row[filter.id].includes(filter.value)
```
There are just too many ways to sort to cover them all.

Closing.

**Closed by gary-menzel** 2018-04-24 10:41 UTC
