### ISSUE TITLE
Wrong component check in Cell

### ISSUE THREAD

**Issue by jebarjonet** [react-tools/react-table#904] opened 2018-04-11 12:45 UTC
The component check in `Cell` seems to malfunction here https://github.com/react-tools/react-table/blob/master/src/utils.js#L212

When passing a custom React Component it does not recognize it as a `Component` and tries to run it as a function:

<img width="432" alt="screen shot 2018-04-11 at 14 48 56" src="https://user-images.githubusercontent.com/4401230/38617498-7e916a44-3d97-11e8-906e-7dd7972d3a1f.png">

The code looks like:

```js
class CustomCell extends React.Component {
  render() {
    return <div>Content</div>;
  }
}

// ...

// in columns definition
{
  Header: "First Name",
  accessor: "firstName",
  Cell: CustomCell
}
```

This is due to an update here: https://github.com/react-tools/react-table/pull/117

The correct solution could be:

```js
Comp.prototype.isReactComponent || Object.getPrototypeOf(Comp).isReactComponent

// instead of
Object.getPrototypeOf(Comp).isReactComponent
```

The problem it solved was this one: https://github.com/react-tools/react-table/issues/109#issue-211754060

Case reproduced here: https://codesandbox.io/s/n07jm1kxqp

**Comment by Flashwit** [comment] 2018-05-23 20:22
Thanks, I've had this exact issue and I'm glad that it's confirmed to be a problem.
I might also suggest

`Object.prototype.isPrototypeOf.call(React.Component,Comp)` as `isReactComponent` is an undocumented property that is subject to change without notice at any time.

**Comment by gary-menzel** [comment] 2018-05-24 02:37
Unfortunately - it does not work and is unlikely to get a PR released.  You will need to pass it as a function that returns the component.

`Cell: (props) => <YouComponent {...props} />`

**Comment by Flashwit** [comment] 2018-05-24 15:51
Ok, well it doesn't work at the moment either. Is the 'fix' for this actually just a documentation update to remove the reference to being able to use React classes for these Renderers?

**Comment by tannerlinsley** [comment] 2018-05-24 22:42
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!

**Closed by tannerlinsley** 2018-05-24 22:42 UTC

**Comment by anthonychung14** [comment] 2018-09-14 15:29
BTW @Flashwit I confirm that returning a Class works for me. Ran into the same issue.
