### ISSUE TITLE
Expanded should use index property (not viewIndex)

### ISSUE THREAD

**Issue by PhobosX** [react-tools/react-table#895] opened 2018-04-05 15:49 UTC
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
When you use expanding and sorting there is na bug.
Expanded is propably using viewIndex property, and it should use index property. 
When you try sort expanded data, and expanded row change its viewIndex it is collapsed,
and the new row that appers on old viewIndex is expanded.

## What are the steps to reproduce the issue?
https://react-table.js.org/#/story/controlled-component

1.try to expand row 2, 
2.sort it by "LAST NAME" - as you see after sorting: row on viewIndex=1(row 2)  is expanded, not row that you expand at point 1.

Can you change the expander to work with index property not viewIndex.

I need to have same rows expanded before/after sorting

**Comment by gary-menzel** [comment] 2018-04-06 10:36
This would be a completely breaking change - so is unlikely to happen until the next major version change (at which point ReactTable may be completely redesigned).  So it can't changed easily at this point due to so many uses depending on the existing behaviour.

NOTE: this is not a bug - it is intended behaviour.  ReactTable does not track the expanded/collapsed state of all records in the data.  It is specifically designed to only track what is displayed on the page.

However, you are welcome to fork the code and change it in any way that suits your requirements.

**Comment by PhobosX** [comment] 2018-04-09 07:52
Do you have any idea how such behavior (expanding same rows before/after sorting) can be programmed in current version (without changing react-table code)?

**Comment by gary-menzel** [comment] 2018-04-09 09:16
I have ideas - but I have never coded any of them.  You would need to create your own map of what is open based on ID's of your rows (note: ReactTable has no internal IDs which is part of the reason why it doesn't use them).  Then you would use something like a getTrProps or getTdProps to know when the particular row was being displayed and set up your `expanded` accordingly.

**Comment by gary-menzel** [comment] 2018-04-13 23:14
I am closing this now as it is an implementation issue.  Some people over on the react-table Slack channel (badge at the top of the README in the doco site) may have done something like this (but I doubt it - the effort is extreme).

**Closed by gary-menzel** 2018-04-13 23:14 UTC
