### ISSUE TITLE
Horizontal scroll bar issue

### ISSUE THREAD

**Issue by binaryj** [react-tools/react-table#534] opened 2017-10-05 15:37 UTC
Versions:
6.5.3
6.6.0
![screen shot 2017-10-05 at 8 57 32 am](https://user-images.githubusercontent.com/32201953/31236205-8317ab1a-a9c1-11e7-849e-c0685a1d0898.png)
![screen shot 2017-10-05 at 8 57 57 am](https://user-images.githubusercontent.com/32201953/31236222-8b3c6a9c-a9c1-11e7-9fd5-cef631190d80.png)

When resizing a column on a table that doesn't have enough columns to make it horizontally scrollable and already has a vertical scroll bar, you can resize a column outside the width of the table like you would expect. However, the headers and body of the table have the undesired side effect of gaining additional horizontal scroll bars when there should only be one scroll bar for the body. You can reproduce this on your current demo.

https://codesandbox.io/s/4qrlxjpv9w

**Comment by gary-menzel** [comment] 2017-10-06 07:53
I was easily able to replicate this (although I am not yet exactly sure why it is happening - it may be the final 'sizer' on the last column that is causing the discrepancy).  I'll do some checking and see if that looks like the issue and provide additional info.

**Comment by erinknight242** [comment] 2017-11-09 21:39
I have this issue, too; it happens on any table with a height or min-height set, if the browser window is narrow enough to force horizontal scroll, you don't have to change column size.

https://codesandbox.io/s/o5np5p0nrz

**Comment by realfresh** [comment] 2017-11-13 09:44
Noticing the same thing as well, a potential solution for certain browsers might be to just override the scrollbar style to something slim.

**Comment by SyedSaifAli** [comment] 2017-11-13 13:11
Having the same issue, and in my case, there are so many headers, so I need min-height or height fixed so that my headers for table show remain visible. But in IO's phones, I am unable to scroll horizontally, although i can vertically.

**Comment by gary-menzel** [comment] 2017-11-13 13:19
While I can make this happen when I try based on what has been reported it is only in rare circumstances. If someone has a PR to address it reliably then it can be pulled in but it really has to be worked on by people who are experiencing it. I've had no problems (scrolling all directions, sizing columns, etc.) using react-table on an iPhone (but I use Chrome). It was definitely designed for mobile use.

**Comment by SyedSaifAli** [comment] 2017-11-13 14:21
@gary-menzel  Thanks for replying, Have you used style prop of ReactTable while using it on iPhone. I've got around 16-18 headers on my table and because of giving height as a prop to style to set the headers still I am unable to scroll.

**Comment by SyedSaifAli** [comment] 2017-11-13 14:38
Ya, so currently we are using both desktop and mobile to access that particular data in react table.
So do I conditionally set the style prop based on checking the userAgent?

**Comment by gary-menzel** [comment] 2017-11-13 14:40
I guess you could do it that way.  I just avoid using 'height' and work with react-table being paged regardless of the device.

**Comment by gary-menzel** [comment] 2017-11-13 14:43
These are really more implementation questions and best asked on the #react-table Slack channel (badge at the top of the readme in the doco).  I can see there is some strange behaviour but the github issue needs to be focussed on getting a PR for a change to fix it (workarounds are better discussed in the wider forum).

**Comment by SyedSaifAli** [comment] 2017-11-13 15:01
Ok, thanks a lot @gary-menzel 👍

**Comment by jpatel3** [comment] 2017-12-05 11:27
The multiple scrollbars happen only in the Safari. Is there any style override to avoid it?

**Comment by trident-ms** [comment] 2017-12-07 16:43
It' caused by the vertical scroll bar in .ReactTable .rt-tbody element.
Add this css definition:
 .ReactTable .rt-tbody {
	overflow-x: hidden!important;
}

**Comment by phoz78** [comment] 2018-05-17 14:42
See https://codesandbox.io/s/oo9j4z1139 for a horizontal scrollbar implementation I've created.

**Comment by tannerlinsley** [comment] 2018-05-24 22:55
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!

**Closed by tannerlinsley** 2018-05-24 22:55 UTC
Labels: Priority:Low, bug

**Comment by lindyw** [comment] 2020-10-13 12:18
Besides @trident-ms 's approach, if you want to get rid of the double scrolling bar without disabling the scrolling function, 
you can remove the following css style under .ReactTable .rt-tbody 
 **// -webkit-box-align: stretch;
  // -ms-flex-align: stretch;
  // align-items: stretch;**

without removing **overflow:auto** nor adding **overflow-x: hidden !important;**
